package org.training.issuetracker.model.dao.xml;

public class Constants {
	public static final String XML_PATH = "xml/";
	public static final String BUILDS_XML_FILENAME = XML_PATH + "Builds.xml";
	public static final String ISSUES_XML_FILENAME = XML_PATH + "Issues.xml";
	public static final String KEY_ASSIGNEE_ID = "assignee-id";
	public static final String KEY_BUILD = "build";
	public static final String KEY_BUILS = "builds";
	public static final String KEY_BUILD_FOUND_ID = "build-found-id";
	public static final String KEY_CREATE_DATE = "create-date";
	public static final String KEY_CREATED_BY_ID = "created-by-id";
	public static final String KEY_DESCRIPTION = "description";
	public static final String KEY_EMAIL = "email";
	public static final String KEY_FIRST_NAME = "first-name";
	public static final String KEY_ID = "id";
	public static final String KEY_ISSUES = "issues";
	public static final String KEY_LAST_NAME = "last-name";
	public static final String KEY_LOGIN = "login";
	public static final String KEY_MANAGER_ID = "manager-id";
	public static final String KEY_MODIFIED_BY_ID = "modified-by-id";
	public static final String KEY_MODIFY_DATE = "modify-date";
	public static final String KEY_NAME = "name";
	public static final String KEY_PASSWORD = "password";
	public static final String KEY_PRIORITY_ID = "priority-id";
	public static final String KEY_PROJECT_ID = "project-id";
	public static final String KEY_RESOLUTION_ID = "resolution-id";
	public static final String KEY_ROLE = "role";
	public static final String KEY_STATUS_ID = "status-id";
	public static final String KEY_SUMMARY = "summary";
	public static final String KEY_TYPE_ID = "type-id";
	public static final String KEY_USER = "user";
	public static final String PRIORITIES_XML_FILENAME = XML_PATH + "Priorities.xml";
	public static final String PROJECTS_XML_FILENAME = XML_PATH + "Projects.xml";
	public static final String RESOLUTIONS_XML_FILENAME = XML_PATH + "Resolutions.xml";
	public static final String STATUSES_XML_FILENAME = XML_PATH + "Statuses.xml";
	public static final String TYPES_XML_FILENAME = XML_PATH + "Types.xml";
	public static final String USERS_XML_FILENAME = XML_PATH + "Users.xml";
	public static final String MESSAGE_UNSUPPORTED_OPERATION = "Unsupported operation";
}